name: Publish to NPM
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy platform binaries to packages
        run: |
          # Windows x64
          cp src/dependencies/finger-print-me-not-64.dll packages/fingerprint-me-not-win32-x64/
          # Windows ia32
          cp src/dependencies/finger-print-me-not-32.dll packages/fingerprint-me-not-win32-ia32/
          # Linux x64
          cp src/dependencies/finger-print-me-not-amd64.so packages/fingerprint-me-not-linux-x64/
          # Linux x86
          cp src/dependencies/finger-print-me-not-x86.so packages/fingerprint-me-not-linux-x86/
          # Linux ARM64
          cp src/dependencies/finger-print-me-not-arm64.so packages/fingerprint-me-not-linux-arm64/
          # macOS x64
          cp src/dependencies/finger-print-me-not-x86.dylib packages/fingerprint-me-not-darwin-x64/
          # macOS ARM64
          cp src/dependencies/finger-print-me-not-arm64.dylib packages/fingerprint-me-not-darwin-arm64/

      - name: Publish platform packages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          for pkg in packages/*; do
            if [ -d "$pkg" ]; then
              cd "$pkg"
              npm publish --access public
              cd ../..
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish main package
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
